[tool.poetry]
name = "opentile"
version = "0.1.0"
description = "[Read tiles from wsi-TIFF files]"
authors = ["Erik O Gabrielsson <erik.o.gabrielsson@sectra.com>"]
licence = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/imi-bigpicture/opentile"
keywords = "whole slide image, digital pathology,, tiff"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
tifffile = "^2021.6.14"
numpy = "^1.21.2"
PyTurboJPEG = "^1.6.1"
Pillow = "^8.3.2"
imagecodecs = "^2021.8.26"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-watch = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
